"""create_vocabulary_table_with_int_id

Revision ID: 69eb848de605
Revises: 1bb6973d1bf2
Create Date: 2026-04-15 17:22:25.896201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69eb848de605'
down_revision: Union[str, Sequence[str], None] = '1bb6973d1bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary',
    sa.Column('word_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('english_word', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('phonetic_transcription', sa.String(), nullable=True),
    sa.Column('raw_storage_url', sa.String(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary')
    # ### end Alembic commands ###
